import { Company } from '@/types';

export const MOCK_COMPANIES: Company[] = [
  {
    id: 1,
    name: 'Acme Manufacturing Ltd',
    companyId: 'COM-001',
    admin: 'Rajesh Kumar',
    adminEmail: 'r.kumar@acme.com',
    branches: 'Kolkata, Delhi',
    activePolicies: '7',
    status: 'Active',
  },
  {
    id: 2,
    name: 'TechFlow Systems Pvt Ltd',
    companyId: 'COM-002',
    admin: 'Sarah Connor',
    adminEmail: 's.connor@techflow.io',
    branches: 'Bangalore',
    activePolicies: '4',
    status: 'Active',
  },
  {
    id: 3,
    name: 'Global Logistics Corp',
    companyId: 'COM-003',
    admin: 'Mike Ross',
    adminEmail: 'm.ross@globallog.com',
    branches: 'Mumbai, Pune',
    activePolicies: '2',
    status: 'Inactive',
  },
  {
    id: 4,
    name: 'FinServe India Pvt Ltd',
    companyId: 'COM-004',
    admin: 'Priya Mehta',
    adminEmail: 'p.mehta@finserve.in',
    branches: 'Gurgaon, Chennai',
    activePolicies: '12',
    status: 'Active',
  },
  {
    id: 5,
    name: 'Green Energy Corp',
    companyId: 'COM-005',
    admin: 'David Green',
    adminEmail: 'd.green@greencorp.com',
    branches: 'Pune',
    activePolicies: '3',
    status: 'Active',
  },
  {
    id: 6,
    name: 'Pinnacle Constructions',
    companyId: 'COM-006',
    admin: 'Arun Verma',
    adminEmail: 'a.verma@pinnacle.in',
    branches: 'Hyderabad',
    activePolicies: '5',
    status: 'Active',
  },
  {
    id: 7,
    name: 'SkyTrade Exports Ltd',
    companyId: 'COM-007',
    admin: 'Nalini Shah',
    adminEmail: 'n.shah@skytrade.com',
    branches: 'Ahmedabad',
    activePolicies: '1',
    status: 'Inactive',
  },
  {
    id: 8,
    name: 'Meridian Pharma Ltd',
    companyId: 'COM-008',
    admin: 'Sanjay Patel',
    adminEmail: 's.patel@meridian.in',
    branches: 'Vadodara, Surat',
    activePolicies: '9',
    status: 'Active',
  },
];
