import { Company } from '@/types';

export const MOCK_COMPANIES: Company[] = [
  {
    id: 1,
    name: 'Acme Manufacturing Ltd',
    companyId: 'COM-001',
    admin: 'Rajesh Kumar',
    adminEmail: 'r.kumar@acme.com',
    branches: 'Kolkata, Delhi',
    activePolicies: '7',
    status: 'Active',
    email: 'info@acme.com',
    mobile_number: '9876543210',
    address: 'Kolkata, West Bengal',
    gst_number: '27AADCB2230M1Z2',
  },
  {
    id: 2,
    name: 'TechFlow Systems Pvt Ltd',
    companyId: 'COM-002',
    admin: 'Sarah Connor',
    adminEmail: 's.connor@techflow.io',
    branches: 'Bangalore',
    activePolicies: '4',
    status: 'Active',
    email: 'contact@techflow.io',
    mobile_number: '9123456780',
    address: 'Bangalore, Karnataka',
    gst_number: '29AADCT1234M1Z1',
  },
  {
    id: 3,
    name: 'Global Logistics Corp',
    companyId: 'COM-003',
    admin: 'Mike Ross',
    adminEmail: 'm.ross@globallog.com',
    branches: 'Mumbai, Pune',
    activePolicies: '2',
    status: 'Inactive',
    email: 'info@globallog.com',
    mobile_number: '',
    address: 'Mumbai, Maharashtra',
    gst_number: '',
  },
  {
    id: 4,
    name: 'FinServe India Pvt Ltd',
    companyId: 'COM-004',
    admin: 'Priya Mehta',
    adminEmail: 'p.mehta@finserve.in',
    branches: 'Gurgaon, Chennai',
    activePolicies: '12',
    status: 'Active',
    email: 'support@finserve.in',
    mobile_number: '9988776655',
    address: 'Gurgaon, Haryana',
    gst_number: '06AADCF5678M1Z3',
  },
  {
    id: 5,
    name: 'Green Energy Corp',
    companyId: 'COM-005',
    admin: 'David Green',
    adminEmail: 'd.green@greencorp.com',
    branches: 'Pune',
    activePolicies: '3',
    status: 'Active',
    email: 'hello@greencorp.com',
    mobile_number: '',
    address: 'Pune, Maharashtra',
    gst_number: '',
  },
  {
    id: 6,
    name: 'Pinnacle Constructions',
    companyId: 'COM-006',
    admin: 'Arun Verma',
    adminEmail: 'a.verma@pinnacle.in',
    branches: 'Hyderabad',
    activePolicies: '5',
    status: 'Active',
    email: 'office@pinnacle.in',
    mobile_number: '9012345678',
    address: 'Hyderabad, Telangana',
    gst_number: '36AADCP9012M1Z4',
  },
  {
    id: 7,
    name: 'SkyTrade Exports Ltd',
    companyId: 'COM-007',
    admin: 'Nalini Shah',
    adminEmail: 'n.shah@skytrade.com',
    branches: 'Ahmedabad',
    activePolicies: '1',
    status: 'Inactive',
    email: 'trade@skytrade.com',
    mobile_number: '',
    address: 'Ahmedabad, Gujarat',
    gst_number: '',
  },
  {
    id: 8,
    name: 'Meridian Pharma Ltd',
    companyId: 'COM-008',
    admin: 'Sanjay Patel',
    adminEmail: 's.patel@meridian.in',
    branches: 'Vadodara, Surat',
    activePolicies: '9',
    status: 'Active',
    email: 'contact@meridian.in',
    mobile_number: '9876501234',
    address: 'Vadodara, Gujarat',
    gst_number: '24AADCM3456M1Z5',
  },
];
