import { RepositoryDocument } from '@/types';

export const MOCK_DOCUMENTS: RepositoryDocument[] = [
  {
    id: 'DOC-001',
    name: 'Fire Policy POL-2024-001.pdf',
    fileType: 'PDF',
    policyId: 'POL-001',
    policyNumber: 'POL-2024-001',
    companyName: 'Acme Manufacturing Ltd',
    uploadedOn: '2024-04-05',
    uploadedBy: 'Rajesh Kumar',
    sizeKb: 1240,
  },
  {
    id: 'DOC-002',
    name: 'Marine Policy COI POL-2024-002.pdf',
    fileType: 'PDF',
    policyId: 'POL-002',
    policyNumber: 'POL-2024-002',
    companyName: 'Acme Manufacturing Ltd',
    uploadedOn: '2024-06-03',
    uploadedBy: 'Rajesh Kumar',
    sizeKb: 890,
  },
  {
    id: 'DOC-003',
    name: 'Liability Policy Schedule.pdf',
    fileType: 'PDF',
    policyId: 'POL-003',
    policyNumber: 'POL-2024-003',
    companyName: 'TechFlow Systems Pvt Ltd',
    uploadedOn: '2024-01-10',
    uploadedBy: 'Sarah Connor',
    sizeKb: 560,
  },
  {
    id: 'DOC-004',
    name: 'Health Policy Members List.xlsx',
    fileType: 'XLSX',
    policyId: 'POL-005',
    policyNumber: 'POL-2024-005',
    companyName: 'FinServe India Pvt Ltd',
    uploadedOn: '2024-04-12',
    uploadedBy: 'Priya Mehta',
    sizeKb: 204,
  },
  {
    id: 'DOC-005',
    name: 'Engineering Policy Inspection Report.pdf',
    fileType: 'PDF',
    policyId: 'POL-006',
    policyNumber: 'POL-2024-006',
    companyName: 'FinServe India Pvt Ltd',
    uploadedOn: '2024-05-20',
    uploadedBy: 'Priya Mehta',
    sizeKb: 2100,
  },
  {
    id: 'DOC-006',
    name: 'Fire Policy Premium Receipt.pdf',
    fileType: 'PDF',
    policyId: 'POL-007',
    policyNumber: 'POL-2024-007',
    companyName: 'Green Energy Corp',
    uploadedOn: '2024-02-05',
    uploadedBy: 'David Green',
    sizeKb: 128,
  },
  {
    id: 'DOC-007',
    name: 'Engineering Policy Drawings.pdf',
    fileType: 'PDF',
    policyId: 'POL-008',
    policyNumber: 'POL-2024-008',
    companyName: 'Pinnacle Constructions',
    uploadedOn: '2024-03-08',
    uploadedBy: 'Arun Verma',
    sizeKb: 7800,
  },
];
